### ISSUE TITLE
sanitizer_report plugin fails with python 3.5

### ISSUE THREAD

**Issue by sumanth-nirmal** [colcon/colcon-sanitizer-reports#17]
`sanitizer_report` plugin for colcon test fails with python 3.5 

- Operating System:
  - Ubuntu 16.04, 4.15.0-46-generic, python 3.5.2
- Installation type:
  - From source
- Version or commit hash:
  - Crystal
- DDS implementation:
  - Fast-RTPS 
- Client library (if applicable):
  - rclpy

### Steps to reproduce

1. Installed `sanitizer_report` as here https://github.com/colcon/colcon-sanitizer-reports/blob/master/README.rst#tutorial---fixing-ros-2-asantsan-issues
2. Compile using 
```sh
$ colcon build --mixin asan-gcc --packages-up-to rcl
```
The compilation gives the following error:
```sh
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.event_handler.sanitizer_report': invalid syntax (sanitizer_report.py, line 29)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/local/lib/python3.5/dist-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/colcon_sanitizer_reports-0.1.0-py3.5.egg/colcon_sanitizer_reports/event_handlers/sanitizer_report.py", line 29
    ENABLED_BY_DEFAULT: bool = False
```

variable syntax anaotations is not available in python 3.5

**Comment by cevans87** [comment]
It looks like we missed Python 3.5 in the CI config
https://github.com/colcon/colcon-sanitizer-reports/blob/master/azure-pipelines.yml

We should add it and fix any Python3.5 compatibility issues.
